language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
  - npm install -g yarn
script:
  - yarn install
  - yarn run build
addons:
  artifacts: true

env:
  global:
    - ORG=PoliticcInc
branches:
  only:
  - master
